font:

  normal:
    family: Roboto Mono for Powerline

    style: Regular

  bold:
    family: Roboto Mono for Powerline

  italic:
    family: Roboto Mono for Powerline

  size: 8.0

  offset:
    x: 0
    y: 0


colors:

  primary:
    background: '0x000000'
    foreground: '0xffffff'

  normal:
    black:   '0x282828'
    red:     '0xf92672'
    green:   '0xa6e22e'
    yellow:  '0xf4bf75'
    blue:    '0x66d9ef'
    magenta: '0xae81ff'
    cyan:    '0xa1efe4'
    white:   '0xf8f8f2'

  bright:
    black:   '0x757575'
    red:     '0xf92672'
    green:   '0xa6e22e'
    yellow:  '0xf4bf75'
    blue:    '0x66d9ef'
    magenta: '0xae81ff'
    cyan:    '0xa1efe4'
    white:   '0xf9f8f5'

