#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d browse chat term dev V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8
bspc config top_padding          0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# nord background
hsetroot -solid "#4C566A" &

# colors
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"

# no stupid x
exec xsetroot -cursor_name left_ptr 
